// This is generated by gen_def.c


struct timeval { uint8_t byte[16]; };
struct timezone { uint8_t byte[8]; };
struct stat { uint8_t byte[144]; };
struct sockaddr { uint8_t byte[16]; };
struct servent { uint8_t byte[32]; };
struct protoent { uint8_t byte[24]; };
typedef unsigned socklen_t;

struct addrinfo {
    int              ai_flags;
    int              ai_family;
    int              ai_socktype;
    int              ai_protocol;
    socklen_t        ai_addrlen;
    struct sockaddr *ai_addr;
    char            *ai_canonname;
    struct addrinfo *ai_next;
};
